import sys
import os
import re
import shtab

# Add src to path
sys.path.insert(0, os.path.abspath("src"))

from git_tools.commit_stats import get_parser as get_commit_parser
from git_tools.pack_stats import get_parser as get_pack_parser
from git_tools.repo_manager import get_parser as get_repo_parser


def get_zsh_functions(script):
    """Extract only the _shtab functions from the generated script."""
    # Matches all lines between the first _shtab_ and the typeset -A line
    match = re.search(r"(_shtab_.*)\ntypeset -A opt_args", script, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def generate():
    # Setup parsers
    cp = get_commit_parser()
    cp.prog = "git-commit-stats"
    for action in cp._actions:
        if action.dest == "repo":
            action.complete = shtab.DIR

    pp = get_pack_parser()
    pp.prog = "git-pack-stats"
    for action in pp._actions:
        if action.dest == "repo":
            action.complete = shtab.DIR

    rp = get_repo_parser()
    rp.prog = "git-repo-manager"

    # Bash
    commit_bash = shtab.complete(cp, shell="bash")
    pack_bash = shtab.complete(pp, shell="bash")
    repo_bash = shtab.complete(rp, shell="bash")

    def get_bash_body(script):
        return script.replace("# AUTOMATICALLY GENERATED by `shtab`\n", "").strip()

    with open("completions/git-tools.bash", "w") as f:
        f.write("# Bash completion for git-tools\n\n")
        f.write("# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py\n\n")
        f.write(get_bash_body(commit_bash))
        f.write("\n\n")
        f.write(get_bash_body(pack_bash))
        f.write("\n\n")
        f.write(get_bash_body(repo_bash))
        f.write("\n")

    # Zsh
    commit_zsh = shtab.complete(cp, shell="zsh")
    pack_zsh = shtab.complete(pp, shell="zsh")
    repo_zsh = shtab.complete(rp, shell="zsh")

    with open("completions/git-tools.zsh", "w") as f:
        f.write("#compdef git-commit-stats git-pack-stats git-repo-manager\n\n")
        f.write("# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py\n\n")
        f.write("typeset -A opt_args\n\n")

        # Write functions for all commands
        f.write(get_zsh_functions(commit_zsh))
        f.write("\n\n")
        f.write(get_zsh_functions(pack_zsh))
        f.write("\n\n")
        f.write(get_zsh_functions(repo_zsh))
        f.write("\n\n")

        # Robust dispatcher for Zsh
        f.write("_git_tools_handler() {\n")
        f.write("  local service=${service:-${words[1]:t}}\n")
        f.write("  case $service in\n")
        f.write('    git-commit-stats) _shtab_git_commit_stats "$@" ;;\n')
        f.write('    git-pack-stats) _shtab_git_pack_stats "$@" ;;\n')
        f.write('    git-repo-manager) _shtab_git_repo_manager "$@" ;;\n')
        f.write("  esac\n")
        f.write("}\n\n")

        f.write("if [[ $zsh_eval_context[-1] == eval ]]; then\n")
        f.write("  compdef _git_tools_handler git-commit-stats\n")
        f.write("  compdef _git_tools_handler git-pack-stats\n")
        f.write("  compdef _git_tools_handler git-repo-manager\n")
        f.write("else\n")
        f.write('  _git_tools_handler "$@"\n')
        f.write("fi\n")


if __name__ == "__main__":
    generate()
