import sys
import os
import re
import shtab

# Add src to path
sys.path.insert(0, os.path.abspath("src"))

from git_tools.commit_stats import get_parser as get_commit_parser
from git_tools.pack_stats import get_parser as get_pack_parser

def get_zsh_functions(script):
    """Extract only the _shtab functions from the generated script."""
    # Matches all lines between the first _shtab_ and the typeset -A line
    match = re.search(r'(_shtab_.*)\ntypeset -A opt_args', script, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""

def generate():
    # Setup parsers
    cp = get_commit_parser()
    cp.prog = "git-commit-stats"
    for action in cp._actions:
        if action.dest == 'repo':
            action.complete = shtab.DIR

    pp = get_pack_parser()
    pp.prog = "git-pack-stats"
    for action in pp._actions:
        if action.dest == 'repo':
            action.complete = shtab.DIR

    # Bash
    commit_bash = shtab.complete(cp, shell="bash")
    pack_bash = shtab.complete(pp, shell="bash")

    def get_bash_body(script):
        return script.replace("# AUTOMATICALLY GENERATED by `shtab`\n", "").strip()

    with open("completions/git-tools.bash", "w") as f:
        f.write("# Bash completion for git-tools\n\n")
        f.write("# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py\n\n")
        f.write(get_bash_body(commit_bash))
        f.write("\n\n")
        f.write(get_bash_body(pack_bash))
        f.write("\n")

    # Zsh
    commit_zsh = shtab.complete(cp, shell="zsh")
    pack_zsh = shtab.complete(pp, shell="zsh")

    with open("completions/git-tools.zsh", "w") as f:
        f.write("#compdef git-commit-stats git-pack-stats\n\n")
        f.write("# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py\n\n")
        f.write("typeset -A opt_args\n\n")

        # Write functions for both commands
        f.write(get_zsh_functions(commit_zsh))
        f.write("\n\n")
        f.write(get_zsh_functions(pack_zsh))
        f.write("\n\n")

        # Single dispatcher/registration
        f.write("# Dispatcher/Registration\n")
        f.write("if [[ $zsh_eval_context[-1] == eval ]]; then\n")
        f.write("    # When sourced/evaled, register both functions\n")
        f.write("    compdef _shtab_git_commit_stats git-commit-stats\n")
        f.write("    compdef _shtab_git_pack_stats git-pack-stats\n")
        f.write("else\n")
        f.write("    # When autoloaded (fpath), dispatch based on $service or $words[1]\n")
        f.write("    local service=${service:-${1:-$words[1]}}\n")
        f.write("    case $service in\n")
        f.write("        git-commit-stats) _shtab_git_commit_stats \"$@\" ;;\n")
        f.write("        git-pack-stats) _shtab_git_pack_stats \"$@\" ;;\n")
        f.write("    esac\n")
        f.write("fi\n")

if __name__ == "__main__":
    generate()
