"""
Shell completion generator for git-tools.

This script uses `shtab` to generate Bash and Zsh completion scripts for
the command-line tools provided by the git_tools package.
"""

import sys
import os
import re
import argparse
import shtab

# Get project root (one level up from this script)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Add src to path
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))

from git_tools.repo_manager import get_parser as get_repo_parser
from git_tools.stats import get_parser as get_stats_parser


def get_zsh_functions(script):
    """
    Extract only the _shtab functions from the generated Zsh script.

    Args:
        script (str): The full Zsh completion script generated by shtab.

    Returns:
        str: The extracted _shtab functions.
    """
    # Matches all lines between the first _shtab_ and the typeset -A line
    match = re.search(r"(_shtab_.*)\ntypeset -A opt_args", script, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def generate():
    """
    Generate Bash and Zsh completion files for all tools.

    This function configures the parsers for `git-stats` and
    `git-repo-manager`, then generates the corresponding completion
    scripts and writes them to the `completions/` directory.
    """
    # Setup parsers
    rp = get_repo_parser()
    rp.prog = "git-repo-manager"

    sp = get_stats_parser()
    sp.prog = "git-stats"
    # Set directory completion for all 'repo' arguments in subcommands
    for action in sp._actions:
        if isinstance(action, argparse._SubParsersAction):
            for subparser in action.choices.values():
                for subaction in subparser._actions:
                    if subaction.dest == "repo":
                        subaction.complete = shtab.DIR

    # Bash
    repo_bash = shtab.complete(rp, shell="bash")
    stats_bash = shtab.complete(sp, shell="bash")

    def get_bash_body(script):
        return script.replace("# AUTOMATICALLY GENERATED by `shtab`\n", "").strip()

    with open(os.path.join(PROJECT_ROOT, "completions/git-tools.bash"), "w") as f:
        f.write("# Bash completion for git-tools\n\n")
        f.write("# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py\n\n")
        f.write(get_bash_body(repo_bash))
        f.write("\n\n")
        f.write(get_bash_body(stats_bash))
        f.write("\n")

    # Zsh
    repo_zsh = shtab.complete(rp, shell="zsh")
    stats_zsh = shtab.complete(sp, shell="zsh")

    with open(os.path.join(PROJECT_ROOT, "completions/git-tools.zsh"), "w") as f:
        f.write("#compdef git-repo-manager git-stats\n\n")
        f.write("# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py\n\n")
        f.write("typeset -A opt_args\n\n")

        # Write functions for all commands
        f.write(get_zsh_functions(repo_zsh))
        f.write("\n\n")
        f.write(get_zsh_functions(stats_zsh))
        f.write("\n\n")

        # Robust dispatcher for Zsh
        f.write("_git_tools_handler() {\n")
        f.write("  local service=${service:-${words[1]:t}}\n")
        f.write("  case $service in\n")
        f.write('    git-repo-manager) _shtab_git_repo_manager "$@" ;;\n')
        f.write('    git-stats) _shtab_git_stats "$@" ;;\n')
        f.write("  esac\n")
        f.write("}\n\n")

        f.write("if [[ $zsh_eval_context[-1] == eval ]]; then\n")
        f.write("  compdef _git_tools_handler git-repo-manager\n")
        f.write("  compdef _git_tools_handler git-stats\n")
        f.write("else\n")
        f.write('  _git_tools_handler "$@"\n')
        f.write("fi\n")


if __name__ == "__main__":
    generate()
