# Zsh completion for git-tools

#compdef git-commit-stats

# AUTOMATICALLY GENERATED by `shtab`


_shtab_git_commit_stats_commands() {
  local _commands=(

  )
  _describe 'git-commit-stats commands' _commands
}

_shtab_git_commit_stats_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)"{-V,--version}"[Show the version and exit.]"
  ":Path to the git repository.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_git_commit_stats_defaults_added=0


_shtab_git_commit_stats() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->git-commit-stats'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_git_commit_stats_defaults_added )); then
    if (( ${_shtab_git_commit_stats_options[(I)${(q)one_or_more}*]} +          ${_shtab_git_commit_stats_options[(I)${(q)remainder}*]} +          ${_shtab_git_commit_stats_options[(I)${(q)default}]} == 0 )); then
      _shtab_git_commit_stats_options+=(': :_shtab_git_commit_stats_commands' '*::: :->git-commit-stats')
    fi
    _shtab_git_commit_stats_defaults_added=1
  fi
  _arguments -C -s $_shtab_git_commit_stats_options

  case $state in
    git-commit-stats)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_git_commit_stats-$line[1]:"
      case $line[1] in

      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_git_commit_stats -N git-commit-stats
else
  # autoload from fpath, call function directly
  _shtab_git_commit_stats "$@"
fi

#compdef git-pack-stats

# AUTOMATICALLY GENERATED by `shtab`


_shtab_git_pack_stats_commands() {
  local _commands=(

  )
  _describe 'git-pack-stats commands' _commands
}

_shtab_git_pack_stats_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)"{-V,--version}"[Show the version and exit.]"
  ":Path to the git repository.:"
)

# guard to ensure default positional specs are added only once per session
_shtab_git_pack_stats_defaults_added=0


_shtab_git_pack_stats() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->git-pack-stats'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_git_pack_stats_defaults_added )); then
    if (( ${_shtab_git_pack_stats_options[(I)${(q)one_or_more}*]} +          ${_shtab_git_pack_stats_options[(I)${(q)remainder}*]} +          ${_shtab_git_pack_stats_options[(I)${(q)default}]} == 0 )); then
      _shtab_git_pack_stats_options+=(': :_shtab_git_pack_stats_commands' '*::: :->git-pack-stats')
    fi
    _shtab_git_pack_stats_defaults_added=1
  fi
  _arguments -C -s $_shtab_git_pack_stats_options

  case $state in
    git-pack-stats)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_git_pack_stats-$line[1]:"
      case $line[1] in

      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_git_pack_stats -N git-pack-stats
else
  # autoload from fpath, call function directly
  _shtab_git_pack_stats "$@"
fi
