#compdef git-commit-stats git-pack-stats git-repo-manager

# AUTOMATICALLY GENERATED by `shtab` via generate_completions.py

typeset -A opt_args

_shtab_git_commit_stats_commands() {
  local _commands=(

  )
  _describe 'git-commit-stats commands' _commands
}

_shtab_git_commit_stats_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)"{-V,--version}"[Show the version and exit.]"
  ":Path to the git repository.:_files -/"
)

# guard to ensure default positional specs are added only once per session
_shtab_git_commit_stats_defaults_added=0


_shtab_git_commit_stats() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->git-commit-stats'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_git_commit_stats_defaults_added )); then
    if (( ${_shtab_git_commit_stats_options[(I)${(q)one_or_more}*]} +          ${_shtab_git_commit_stats_options[(I)${(q)remainder}*]} +          ${_shtab_git_commit_stats_options[(I)${(q)default}]} == 0 )); then
      _shtab_git_commit_stats_options+=(': :_shtab_git_commit_stats_commands' '*::: :->git-commit-stats')
    fi
    _shtab_git_commit_stats_defaults_added=1
  fi
  _arguments -C -s $_shtab_git_commit_stats_options

  case $state in
    git-commit-stats)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_git_commit_stats-$line[1]:"
      case $line[1] in

      esac
  esac
}

_shtab_git_pack_stats_commands() {
  local _commands=(

  )
  _describe 'git-pack-stats commands' _commands
}

_shtab_git_pack_stats_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)"{-V,--version}"[Show the version and exit.]"
  {-H,--human}"[Display human-readable sizes (e.g., KiB, MiB).]"
  "--loose-uncompressed[Include uncompressed size for loose objects (can be slow).]"
  ":Path to the git repository.:_files -/"
)

# guard to ensure default positional specs are added only once per session
_shtab_git_pack_stats_defaults_added=0


_shtab_git_pack_stats() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->git-pack-stats'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_git_pack_stats_defaults_added )); then
    if (( ${_shtab_git_pack_stats_options[(I)${(q)one_or_more}*]} +          ${_shtab_git_pack_stats_options[(I)${(q)remainder}*]} +          ${_shtab_git_pack_stats_options[(I)${(q)default}]} == 0 )); then
      _shtab_git_pack_stats_options+=(': :_shtab_git_pack_stats_commands' '*::: :->git-pack-stats')
    fi
    _shtab_git_pack_stats_defaults_added=1
  fi
  _arguments -C -s $_shtab_git_pack_stats_options

  case $state in
    git-pack-stats)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_git_pack_stats-$line[1]:"
      case $line[1] in

      esac
  esac
}

_shtab_git_repo_manager_commands() {
  local _commands=(
    "scan:"
  )
  _describe 'git-repo-manager commands' _commands
}

_shtab_git_repo_manager_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)"{-V,--version}"[show program\'s version number and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_git_repo_manager_defaults_added=0

_shtab_git_repo_manager_scan_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_git_repo_manager_scan_defaults_added=0


_shtab_git_repo_manager() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->git-repo-manager'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_git_repo_manager_defaults_added )); then
    if (( ${_shtab_git_repo_manager_options[(I)${(q)one_or_more}*]} +          ${_shtab_git_repo_manager_options[(I)${(q)remainder}*]} +          ${_shtab_git_repo_manager_options[(I)${(q)default}]} == 0 )); then
      _shtab_git_repo_manager_options+=(': :_shtab_git_repo_manager_commands' '*::: :->git-repo-manager')
    fi
    _shtab_git_repo_manager_defaults_added=1
  fi
  _arguments -C -s $_shtab_git_repo_manager_options

  case $state in
    git-repo-manager)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_git_repo_manager-$line[1]:"
      case $line[1] in
        scan) _arguments -C -s $_shtab_git_repo_manager_scan_options ;;
      esac
  esac
}

_git_tools_handler() {
  local service=${service:-${words[1]:t}}
  case $service in
    git-commit-stats) _shtab_git_commit_stats "$@" ;;
    git-pack-stats) _shtab_git_pack_stats "$@" ;;
    git-repo-manager) _shtab_git_repo_manager "$@" ;;
  esac
}

if [[ $zsh_eval_context[-1] == eval ]]; then
  compdef _git_tools_handler git-commit-stats
  compdef _git_tools_handler git-pack-stats
  compdef _git_tools_handler git-repo-manager
else
  _git_tools_handler "$@"
fi
